### ISSUE TITLE
Think about namespaces

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#110]
@andrewthad suggested changing the naming conventions to use the more common assumption that people will import thing other than types qualified. I think it would probably be too disruptive to do that directly. But sharing (or even copying and pasting) code among the different array implementations would be much easier in that regime. I believe there is quite a lot of code that could be shared. That suggests an alternative approach: layer `primitive` on top of another package, in the same repository, that uses the other convention. `primitive` itself would just be a thin shell over the other package.

**Comment by andrewthad** [comment]
As an alternative, it doesn't necessarily have to be a separate package. It could just be different modules in the `primitive` package. This would actually be my preference.

**Comment by cartazio** [comment]
Or vice versa ?

What problem are we trying to solve

**Comment by treeowl** [comment]
@cartazio, there are a decent number of functions (largely in class instances) that are basically the same between `Data.Primitive.Array` and `Data.Primitive.SmallArray`, except for the *names*. I found myself copying definitions, then doing find and replace throughout their bodies. It was annoying. Have you had a chance to look at #109? I'm leaving town tomorrow evening....

**Comment by cartazio** [comment]
i'll do a review of all the PRs in a day or so, been a bit swampped the
past two days with work

**Comment by cartazio** [comment]
at least for now: lets not break / change any current naming conventions for Primitive. At least for preexisting modules

Perhaps it makes sense to relax it for newer modules, but that creates a nonuniformity in naming convention for both users and contributors.   

i definitely think we have no good reason to wholesale rename all the current modules, this would accomplish nothing and needless break everything down stream with no real improvements.

So our choices are:
a) consistency but a teeny bit of extra verbiage (which allows mostly safe unqualified imports)
b) inconsistency (which also forces newer modules to be imported qualified)

After think about this for the past day or so, i remember'd [we reexport everything here](https://hackage.haskell.org/package/primitive-0.6.3.0/docs/Data-Primitive.html)

if we wish to continue to have this module be a good catch all for using all the data structures that Primitive provides, we *must* continue that slightly verbose convention despite the small cost of verbiage.

nothing precludes a wrapper package that exports stuff with the qualified names, but Primitive will not be that package.
