### ISSUE TITLE
add `since` metadata to primitive modules and operations

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#124]
@hvr any thoughts? I think this will help with reasoning about versioning and compatibility etc for users of primitive

**Comment by andrewthad** [comment]
I'm +1 on this. This convention has been adopted in `base`, and it's pretty helpful.

**Comment by chessai** [comment]
Oh, I was just about to open an issue about this. Yes, adding `since` metadata would be extremely useful.

**Comment by chessai** [comment]
Awesome. If you want since pragmas on older stuff or stuff that was introduced before 0.6.4.0 (the upcoming release) i would be willing to make a PR for that

**Comment by andrewthad** [comment]
I'm just doing the 0.6.4.0 stuff since it's still pretty fresh on my mind. It's probably worth doing the older stuff too. The changelog would be really helpful for that.

**Comment by andrewthad** [comment]
Here it is: https://github.com/haskell/primitive/pull/163. Someone should review it, but I think I got everything.

**Comment by chessai** [comment]
I'm pretty sure this can be closed, `since` metadata has been added for everything since version 0.6.0.0
