### ISSUE TITLE
Bump base max version

### ISSUE THREAD

**Issue by spl** [haskell/primitive#13]
In running `dlist` Travis-CI tests, I found that the `primitive` dependency on `base < 4.8` is blocking the build with GHC HEAD. I'm just raising this issue to see if `primitive` does indeed build against HEAD and `base-4.8` (as it now stands) and if this constraint can be lifted.

If `primitive` doesn't build, don't worry about it. There's absolutely no urgency to deal with this.

**Comment by dolio** [comment]
I believe this has been fixed.
