### ISSUE TITLE
Newtype for deriving Storable via Prim

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#130]
There's currently a [paper](https://www.kosmikus.org/DerivingVia/deriving-via-paper.pdf) for the `DerivingVia` extension (no GHC proposal yet though). One application of this is that instances of `Prim`, which I would describe as a better version of `Storable`, give rise to instances of `Storable`. So, we could add a newtype to `Data.Primitive.Types` like this:

```
newtype WrapPrim a = WrapPrim a
instance Prim a => Storable (WrapPrim a) where ...
```

I don't think this should actually be done until it's more certain that `DerivingVia` is going to land, but it would be nice to have. It would save me some boilerplate in projects I've worked on.

cc @Icelandjack

**Comment by cartazio** [comment]
Do the alignment semantics line up for prim types Vis storable and
primitive ? Or are there differences in assumptions?

Probably a reasonable safe thing to consider.

Andrew: maybe these and other ideas would easy to work shop out in a
primitive-experiments layer package on top?  Not sure if that would help
you get your nice things faster too?

**Comment by andrewthad** [comment]
There are no documented semantics for alignment in `primitive`. None of the functions in `primitive` even use `alignment#` since the byte array stuff used `newByteArray#`, which aligns to a machine word. But, let's say that at some point, we added a hypothetical function `alloca` to `Data.Primitive.Ptr` (not that I actually want to add this right now) that matched the behavior of the one in `Foreign.Marshal.Alloc`:

    alloca :: Prim a => (Ptr a -> IO b) -> IO b

It would be expected that such a function would use the alignment from the `Prim` instance. So, yes, I would say that semantics of alignment match, even though they are undocumented.

The experiments package is a good idea. I'll probably start doing proofs-of-concept in something like that.

**Comment by RyanGlScott** [comment]
For what it's worth, you don't necessarily have to wait until `DerivingVia` lands to add this type. It's just a newtype after all, and they're already useful! That way, when `DerivingVia` lands, you'll get additional mileage out of it straight away.
