### ISSUE TITLE
Make compareByteArrays available directly

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#131]
The `Ord` instance for `ByteArray` currently uses `compareByteArrays#` under the hood on GHC 8.4 and newer. However, it would be useful for users to have access to a `compareByteArrays` function for situations where they have built sliced arrays on top of `ByteArray`.

    compareByteArrays :: ByteArray -> Int -> ByteArray -> Int -> Int -> Ordering

A backwards-compatibility shim is already readily available in the code.

**Comment by sjakobi** [comment]
It would be great to have that exported! I don't care about the offsets, but wouldn't mind them either…

**Comment by chessai** [comment]
i have actually wanted this before in my own code. +1

**Comment by andrewthad** [comment]
This will be resolved in https://github.com/haskell/primitive/pull/283. It's got tests in there, but if either of you want to review it, please do so.
