### ISSUE TITLE
Stop reexporting fromList in Data.Primitive.Array

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#132]
Currently, `fromList` and `fromListN` get reexported in `Data.Primitive.Array`. In older GHCs, they aren't reexports. They are top-level definitions. This was done to help backwards-compatibility with GHCs that didn't have the `IsList` typeclass. However, `SmallArray` also has an `IsList` instance, but we cannot do the same trick there since a user of an older GHC would end up with two different definitions of `fromList` in scope if they imported both `Data.Primitive.Array` and `Data.Primitive.SmallArray`.

I would like to propose instead exporting functions named `arrayFromList` and `arrayFromListN` from `Data.Primitive.Array`. This is consistent with how this situation is handled for `SmallArray`. This would be a breaking change, although it would not affect many users, and the fix would just be to import `fromList` and `fromListN` from `GHC.Exts`.

**Comment by treeowl** [comment]
Agreed.

**Comment by RyanGlScott** [comment]
Sounds good to me. If you write a patch for this, don't forget to give `primitive` a major version bump!

**Comment by andrewthad** [comment]
Cool. I'll wait to do this at least until `primitive-0.6.4.0` is released so that users of the two preceeding deprecated releases won't need to do a major version bump to get the fixes.

**Comment by treeowl** [comment]
Also agreed.

**Comment by andrewthad** [comment]
The next release of `primitive` will be a major version bump, so I think now's a good time to do this.

**Comment by cartazio** [comment]
Yeah :)

**Comment by andrewthad** [comment]
Since 0.7 was released without this, this will need to wait for 0.8.

**Comment by cartazio** [comment]
darn, my bad. :) 
i'm not sure what versioning strategy is valid for conditional exports.

that said, i could do a full assay of the impact of the exports

**Comment by cartazio** [comment]
(i hae a setup that lets me grep all of new hackage / hackage tip)
