### ISSUE TITLE
Consistent naming for traversals in PrimMonad

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#134]
Now that the PrimArray branch has landed in master, we have to reconcile naming. I've added some documentation to `Data.Primitive` that explains the naming convention that I propose for traversals/filters/maps in `primitive`. These conventions suggest that `unsafeTraverseArray` and `unsafeTraverseSmallArray` should be named `traverseArrayP` and `traverseSmallArrayP` respectively instead. These haven't been released to hackage yet, so it's still easy to rename them. I wanted to gauge consensus on this. Alternatively, we could pick a different naming scheme (ie- prefix with `unsafe` instead of suffix with `P`), and I could just change the function in `PrimArray` and the docs. @treeowl I think you wrote these two functions, so I would particularly like your input.

**Comment by treeowl** [comment]
I did write those functions. I like having the word `unsafe` in the name, but I'm also okay with the `P` suffix. Should we cut the baby in half and use `unsafeTraverseArrayP`?

**Comment by andrewthad** [comment]
The `P` suffix comes from a desire for brevity. So, doing both would be rather analogous to cutting the baby in half.

I think my mine gripe with the word unsafe is that, when I use these functions, I don't really want to see the word unsafe all over my code. Yes, it's unsafe in the sense that doing it in `ListT IO` will make it not work correctly, but I'm almost universally going to use this in `ST s`, and so the warning for caution just wastes horizontal space on my screen. There are way more easily used unsafely (like the indexing functions) that don't get branded as unsafe.

Another very minor gripe of mine is that the `itraverse` functions start to look weird. Do we do `unsafeITraversePrimArray` or `unsafeItraversePrimArray`?

Maybe we could use unsafe as a suffix. This is uncommon, but:

- `traverseArrayUnsafely`
- `itraversePrimArrayUnsafely`

**Comment by treeowl** [comment]
I guess I can learn to live with just the P suffix. Someone writing a safe
interface can always rename things as needed.

**Comment by cartazio** [comment]
If the unsafe is with respect to the linearity details, all of pritmive is
unsafe.  Any backtracking is not a supported mode of operation even though
the code can support it via the generic monad structures
