### ISSUE TITLE
Export indexArray## with a better name

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#140]
The function `indexArray##` is defined in `Data.Primitive.Array` and used internally. This function is useful to end users as well since `indexArrayM` doesn't work in every monad (and not everyone working with `Array` is even operating in a monadic context). What's a better name for this? Here are some suggestions:

- `indexArray'`
- `indexArrayUnary`
- `indexArrayFinely`
- `indexArrayBox`
- `indexArraySolo`

[This trac ticket](https://ghc.haskell.org/trac/ghc/ticket/14673) is vaguely relevant here, since it could help inspire the name.

**Comment by cartazio** [comment]
Honestly I’m ok with the double hash name personally.  It requires magic
hash  and unboxed tuples  to be enabled AND will never be useable in ghci
due to the lack of unboxed tuple support over there

It’s reaosnable to magic hash name space operations which won’t work in
ghci

**Comment by cartazio** [comment]
once we merge in the associated PR, we good?

**Comment by andrewthad** [comment]
Yes, that should do it.
