### ISSUE TITLE
add MVar support to Primitive

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#148]
this was discussed/planned years ago, but still to do

Are there other ones we should consider too?  Can we safely add StableNames or WeakRefs or Finalizers too?

**Comment by cartazio** [comment]
cc @hvr @bgamari @RyanGlScott @jberryman for ideas :)

**Comment by cartazio** [comment]
STM is definitely off the table because GHC's semantics doesn't support nested transactions, which would be needed to even touch the question of how to sanely consider something like  IO > STM > ST > STM in ST via primitive style PrimMonad stuff

**Comment by cartazio** [comment]
Current plan for Mvar would not include forkIO. ANY efforts for
deterministic concurrency should be in a higher level library.  Unless you
think we can do that sanely and simply ... :)

Other points sound good as starting points

**Comment by andrewthad** [comment]
Mildly relevant to this discussion: https://ghc.haskell.org/trac/ghc/ticket/14195

**Comment by andrewthad** [comment]
I've changed my mind on `StableName`. I think generalizing it is bad for two reasons:

- Practical reason: not having access to `hashStableName` makes it nearly useless.
- Non-determinism reason: `makeStableName` is not deterministic in the presence of optimizations. Additional inlining can cause a computation that would have resulting in False to result in True.

For these reason, I don't think `StableName` is appropriate for `primitive`. Everything provided here should be deterministic.

**Comment by andrewthad** [comment]
This was implemented. Closing.
