### ISSUE TITLE
mconcat broken on SmallArray

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#155]
I recently pushed a new release of `quickcheck-classes`, which is used in the test suite for primitive. In this release, I added additional tests for the methods `mconcat`, `sconcat`, and `stimes`, which belong to `Monoid` and `Semigroup`. I discovered that the implementation of `mconcat` for `SmallArray` is incorrect. I am going to fix this shortly.

**Comment by cartazio** [comment]
Excellent !
