### ISSUE TITLE
Move PrimUnlifted into Data.Primitive.Types

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#160]
`PrimUnlifted` lives in `Data.Primitive.UnliftedArray`, but I think it would make more sense for it to live in `Data.Primitive.Types`. It could be reexported from `Data.Primitive.UnliftedArray` for compatibility purposes. This isn't something I feel particularly strongly about. It just crossed my mind and I thought I'd jot it down.

**Comment by treeowl** [comment]
#196 proposes to move it to its own module, which I think is better. I think `Data.Primitive.Types` itself should almost certainly be broken up into several modules. We can keep it around re-exporting things, of course.

**Comment by treeowl** [comment]
Closed by #196.
