### ISSUE TITLE
keeping track of all the in flight doc cleanups (May - Jun / summer 2018)

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#168]
eg: maybe the new language about ord instances should be phrased better eg "Ord instances aren't guaranteed to be stable over major versions"

theres a few other things like that we have in flight, plus also fixing up / clarifying the parts where we throw around the words affine / linear in the linear logic sense rather than the vector space sense (and most sophisticated users will more likely be familiar with vector spaces than linear logic)

**Comment by andrewthad** [comment]
Closing. Nothing is guaranteed to be stable across major version bumps, so to me it seems redundant to mention that in documentation. Do open a PR though if you'd like to add any clarifications to the way affine or linear are used.
