### ISSUE TITLE
move -wall from .cabal file to travis CI args

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#169]
i nearly did a ghc wall bearing release! @andrewthad @RyanGlScott lets have wall set for the  CI. and or for testing via a testing flag we toggle

**Comment by RyanGlScott** [comment]
@cartazio, to be clear, you want `-Wall` enabled on Travis, but not put into the `.cabal` file itself?

**Comment by cartazio** [comment]
yup.

having Wall in a package release is a bad thing

we could alternatively have it in our cabal.project (possibly the ideal
approach so its on by default for dev but doesn't exist for release)  or
gated by a flag like -fdev
