### ISSUE TITLE
Possible to have a newByteArray which uses calloc to zero memory?

### ISSUE THREAD

**Issue by jberryman** [haskell/primitive#17]
I played around with using `calloc` to allocate a block of memory (via the [missing-foreign](https://hackage.haskell.org/package/missing-foreign-0.1.1/docs/Foreign-Marshal-MissingAlloc.html) package) and found that it was twice as fast as any use of the `copy/set/fill` functions offered in `primitive`. It may be outside the scope of this project, but I wonder if it would be possible to implement such an alternative primop.

Relevant issue I opened in missing-foreign: https://github.com/dagit/missing-foreign/issues/1

**Comment by andrewthad** [comment]
Closing. This would be cool, but really there is nothing that can be done in `primitive` unless GHC adds a primop for this.
