### ISSUE TITLE
Synchronized interface between different array types.

### ISSUE THREAD

**Issue by winterland1989** [haskell/primitive#174]
There're a lot of functions added with module `Data.Primitive.PrimArray` in version 0.6.4. I'm afraid this is making an unified array interface between different array types harder,  IMO there can be some specialized operations within each module, but overall we should provide the same functionality if some operations are common.

So i suggest let's start a synchronization phase after 0.6.4, either by shrinking some interfaces in `PrimArray`,  or by enlarge the other module. I personally suggest we should do both, especially there're some folds/traverse can be implemented using list operations without compromising performance after #173 is implementated.

**Comment by andrewthad** [comment]
Closing. I've been adding some functions to `ByteArray` and `PrimArray` to close these gaps in the API. If you notice functions missing on `master`, open an issue listing them, and we can get them added.
