### ISSUE TITLE
relax upper bound to < 4.13 in master

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#179]
did this for 0.6.4.0 on hackage with meta data edit, lets reflect in CI  etc

**Comment by RyanGlScott** [comment]
@cartazio, all you'd need to do is change this line: https://github.com/haskell/primitive/blob/ef8bf2d962e7783693adfcdde2b986498d7d6536/primitive.cabal#L57

**Comment by cartazio** [comment]
yes, :) 
i did the one already on hackage :)

**Comment by cartazio** [comment]
this is just a todo :)

**Comment by cartazio** [comment]
Thx.  I’ve been a tad hosed with some work stuff I really need to finish
