### ISSUE TITLE
some useful functions remain unexported

### ISSUE THREAD

**Issue by chessai** [haskell/primitive#185]
Data.Primitive.Array.createArray & Data.Primitive.SmallArray.createSmallArray

seem to me like both are totally safe ways of constructing arrays. Is there a reason they are not exported?

**Comment by chessai** [comment]
Also, `zipWith` (defined roughly as zipW in both modules) is a nice monomorphic variant of mzipWith, but I'm not sure it needs to be exported, as it would cause a naming conflict with the prelude, whereas most (all?) of primitive currently avoids doing that

**Comment by cartazio** [comment]
Yeah, we need to take a look st this stuff. You’re right.

**Comment by konsumlamm** [comment]
Other useful functions that I found, but aren't exported are:

* `runByteArray` & `runPrimArray` (`runArray` & `runSmallArray` are already exported)
* `emptyByteArray`, `emptyPrimArray`, `emptyArray`, `emptySmallArray` (to have an easy way to create an empty array)

**Comment by andrewthad** [comment]
I'm fine with exporting the `create` functions, the `run` functions, and the `empty` functions if anyone prepares a PR for it.

**Comment by treeowl** [comment]
Isn't create a little specific?
