### ISSUE TITLE
Doing bad things in pointer equality check for immutable arrays

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#192]
In `Data.Primitive.ByteArray`, we have:

```
sameByteArray :: ByteArray# -> ByteArray# -> Bool
sameByteArray ba1 ba2 =
    case reallyUnsafePtrEquality# (unsafeCoerce# ba1 :: ()) (unsafeCoerce# ba2 :: ()) of
#if __GLASGOW_HASKELL__ >= 708
      r -> isTrue# r
#else
      1# -> True
      0# -> False
#endif
```

The same code is also in the `PrimArray` module because I copied it over there as well. However, I never noticed until now that this code uses `unsafeCoerce#` to go from a type with an unlifted representation to a type with a lifted representation. This doesn't currently seem to cause any problems, but it is in general a dangerous thing to do, and the GHC core linter is supposed to generate a warning when this is happens. I think we could instead use this:

```
sameByteArray :: ByteArray# -> ByteArray# -> Bool
sameByteArray ba1 ba2 =
    case sameMutableByteArray# (unsafeCoerce# ba1) (unsafeCoerce# ba2) of ...
```

This instead coerces to from one unlifted type to another.

**Comment by hvr** [comment]
I've been wondering about this one as well; but I never had the time to investigate (i.e. do Git archeology and read notes) why the `unsafeCoerce x :: ()` approach was taken instead of the `sameMutableByteArray#` one (which iirc has been available for at least a decade in GHC at least).

**Comment by treeowl** [comment]
Let's do it. I don't actually think the current code can go wrong, but I always prefer to use the least illegitimate possible approach.

**Comment by andrewthad** [comment]
This was fixed a while ago. Closing.
