### ISSUE TITLE
PrimUnlifted StablePtr looks sketchy

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#195]
We currently have `PrimUnlifted (StablePtr a)`, but that's a bit troubling. `StablePtr# a` has kind `TYPE 'AddrRep` rather than `TYPE 'UnliftedRep`, which means that even once we have `UnliftedArray#` we won't be able to put a `StablePtr#` into one without `unsafeCoerce#`. Is that coercion safe? I don't personally have a clue; maybe someone who knows more about stable pointers can answer that question.

**Comment by treeowl** [comment]
@simonmar, I suspect you're the one best positioned to answer this question.

**Comment by treeowl** [comment]
That was my concern, but I don't know enough about stable pointers. What does the GC do when it collects the contents of an `ArrayArray#`? What will happen if it encounters a `StablePtr#` in one of the slots? In particular, will it "notice" that the `StablePtr#` is a `StablePtr#` and just do the right thing (in which case we can keep using the instance) or will it crash?

**Comment by treeowl** [comment]
@bgamari, you may know something about this too.

**Comment by treeowl** [comment]
All righty, then. We'd best get this fixed. Thanks, all.

**Comment by andrewthad** [comment]
This instance causes a [compile-time crash for ghcjs 8.4](https://github.com/ghcjs/ghcjs/issues/665). I going to put up a PR removing it.
