### ISSUE TITLE
Quit importing GHC.Prim

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#197]
There are still one or two modules that import `GHC.Prim`. We should *never* do this. The approved place to grab the primitive stuff is `GHC.Exts`. Among other things, primitives can *go away* and be replaced by compatibility functions that will not be in `GHC.Prim`.

**Comment by andrewthad** [comment]
Agreed. There is no reason to import `GHC.Prim` ever.

**Comment by hvr** [comment]
@treeowl who says that?! I was always under the impression that `GHC.Exts` was a wart, and that everyone who needs to access primitives ought to reach for `GHC.Prim` instead; hence I've been slowly moving away from importing GHC.Exts whenever I had a chance...

**Comment by treeowl** [comment]
@hvr, the second sentence in the Haddocks for `GHC.Prim`. :-D We've already been bitten by this in the replacement of `atomicModifyMutVar#` by `atomicModifyMutVar2#`.

**Comment by treeowl** [comment]
Closed in #236.
