### ISSUE TITLE
Support for new SmallArray# family of types and functions in GHC 7.10

### ISSUE THREAD

**Issue by jberryman** [haskell/primitive#20]
I suppose the options are:

  - break compatibility with old `base` and support `SmallArray#` as a wrapper in the usual way

  - export an opaque `SmallArray` type that conditionally wraps `SmallArray#` else `Array#` for old versions

  - Make `Array`/`MutableArray` opaque (causing breakage for some, but probably not most users) something like:

        data Array a = Array (Array# a) 
        #if __GLASGOW_HASKELL__ >= 710
                     | SmallArray (SmallArray# a)
        #endif

    ...and then just provide an additional `newSmallArray` function, plus support small arrays in existing `copy/clone/etc` functions.

Other ideas? I'd be happy to try to submit a patch if we can figure out the best approach.

**Comment by jberryman** [comment]
Now that I'm looking at my own code, I would very much prefer the third option as a user; otherwise it's quite a pain to even try out small arrays and I think users will end up not using `primitive` and just implementing this proposal themselves.

Then I suppose exposing the constructor(s) in an `Internal` module is the best choice. Thoughts?

**Comment by cartazio** [comment]
@jberryman  pring

**Comment by cartazio** [comment]
i do think that anything we add to the primitive package shoulnd't be such that it hinders the performance minded users

**Comment by ekmett** [comment]
It strikes me that it probably belongs as its own `SmallArray` type.

**Comment by dolio** [comment]
Small arrays have been merged.
