### ISSUE TITLE
Need a bugfix release

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#200]
Once we've fixed #195 and #199, we should probably make a minor release. Namely:

1. Remove the `PrimUnlifted StablePtr` instance, which is basically guaranteed to segfault and which can't be fixed in any useful way.

2. Fix the `PrimUnlifted (SmallArray a)` and `PrimUnlifted (SmallMutableArray s a)` instances for GHC versions that don't have `SmallArray#`. These will segfault because they try to coerce between boxed `Array`s and unboxed `ArrayArray#`s.

**Comment by treeowl** [comment]
While we're at it, we should backport the import change `GHC.Prim` -> `GHC.Exts` for `Data.Primitive.MutVar` for compatibility with GHC HEAD.

**Comment by treeowl** [comment]
The commits we need (as far as I know) are 

Fix PrimUnlifted instances for small arrays (#203)
committed by treeowl ⋅ 4709d484
andrewthad

remove PrimUnlifted instance for StablePtr (#202)
committed by andrewthad ⋅ 96c67699
Aug 14, 2018
treeowl

Fix atomicModifyMutVar'
committed by treeowl ⋅ 2a63e114

**Comment by ndmitchell** [comment]
Looking at the tickets linked, I note they are all now marked closed. The `GHC.Prim -> GHC.Exts` change would also be useful for me.

**Comment by cartazio** [comment]
Roger that.

I think I did most of these fixes in master. But I’ll check this evening
after dinner or tomorrow (birthday weekend with fam atm )

**Comment by andrewthad** [comment]
Closing. I believe this was done a while ago.
