### ISSUE TITLE
Add more `Prim` and `PrimUnlifted` tests

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#205]
We need to make sure that *all* the `Prim` instances work. It looks to me as though we test less than a handful. This is how we missed the fact that the `PrimUnlifted` instances for `SmallArray a` and `SmallMutableArray a` were wrong for older GHC versions.

**Comment by treeowl** [comment]
Actually, trying for all the `PrimUnlifted` things seems like overkill. But we definitely should try for all the `Prim` ones.

**Comment by chessai** [comment]
What is the status of this? I know @andrewthad added `primLaws` to `quickcheck-classes` some time ago, but I don't know how well-covering it is.

**Comment by andrewthad** [comment]
The `primLaws` function tests all of the typeclass methods. This issue would be resolved by adding tests for the `Prim` instances of `CInt`, `CBool`, etc. to the `primitive` test suite, which just involves some copy and paste.

**Comment by cartazio** [comment]
@andrewthad can you split out the primlaws you currently use into a seperate package from the base QC classes? otherwise it really makes having the official version of those tests correctly tracked/used in primitive an uholly pain and complicates our build system

**Comment by andrewthad** [comment]
This has been completed.
