### ISSUE TITLE
Check that FFI array code makes sense

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#206]
In `Data.Primitive.Internal.Operations`, we define `set{type}Array#` to be the same as `set{type}OffAddr#` for each type. This looks *extremely* fishy. A `MutableByteArray#` starts with a closure header and a size field. I think we're supposed to skip over those to get to the start of the array proper. See `BYTE_ARR_CTS` in `includes/Cmm.h` in the GHC source tree, which skips over `SIZEOF_StgArrBytes` to get to the beginning of the array. I don't know the appropriate way for `primitive` to get the necessary information.

**Comment by treeowl** [comment]
Ahh...... Now I understand. This is FFI magic of the highest order. The FFI compiler treats `MutableByteArray#` specially. Weird stuff.

**Comment by andrewthad** [comment]
I've opened an [issue on the GHC gitlab](https://gitlab.haskell.org/ghc/ghc/issues/16629) for the lack of documentation on this subject.
