### ISSUE TITLE
Convenience classes

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#211]
The state token type can be annoying to handle in constraints. I'd like something like

```haskell
class (PrimMonad m, PrimState m ~ s) => PrimMonadOn s m
instance (PrimMonad m, PrimState m ~ s) => PrimMonadOn s m

class (PrimBase m, PrimState m ~ s) => PrimBaseOn s m
instance (PrimBase m, PrimState m ~ s) => PrimBaseOn s m
```

I'm not fussy about the names.

**Comment by ekmett** [comment]
I'd suggest `MonadPrim` and, less assuredly, something like `MonadPrimBase`.

That way you could use them in the style of the `mtl` classes, and never even notice the type families for most users.

**Comment by cartazio** [comment]
that does sound like a reasonable bikeshed color Ed

**Comment by chessai** [comment]
i wanted this, so for the time being i put it in this package: https://github.com/haskell-primitive/primitive-convenience

it's not on hackage. the name 'primitive-convenience' is also bad. i'd rather have this in primitive, and not a separate package, since it does make working with primmonad less annoying.

**Comment by ekmett** [comment]
@chessai could you add MonadPrimBase?

**Comment by cartazio** [comment]
Im halpybto add this too.  Though I may not get to it till after icfp next
month

**Comment by chessai** [comment]
@ekmett done. Check master

**Comment by cartazio** [comment]
@chessai https://github.com/haskell-primitive/primitive-convenience/commit/1fc04b3bd21c5a80766e2777a9dd8a11f63136c7 i'm looking at that ... are you sure those should all be monad PrimBase instances?

**Comment by cartazio** [comment]
the only not ST/IO/STE primBase instance is IdentityT ...

**Comment by chessai** [comment]
Ah, I made a mistake. I copy-pasted in my phone and changed all the
relevant identifiers.

https://github.com/haskell-primitive/primitive-convenience/commit/1816796ae3a69e2fc74f825b07de269bad1be109
fixes this.

**Comment by ekmett** [comment]
class (PrimBase m, s ~ PrimState m) => MonadPrimBase s m | m -> s
    instance (PrimBase m, s ~ PrimState m) => MonadPrimBase s m 

using UndecidableInstances, etc. would be a more robust definition.

Then the user literally can't care about whether or not they are using fundeps and this class or the original class.

As it is you have to actually distinguish between having this convenience class, which is not implied by the usual constraint and having the original class.

**Comment by hsenag** [comment]
Can't you just use a constraint synonym?

**Comment by ekmett** [comment]
Constraint synonyms cannot be partially applied and are strictly less useful.

Here you can meaningfully talk about `MonadPrim :: * -> (* -> *) ->*`. With a constraint synonym you cannot.

**Comment by cartazio** [comment]
agree with ed's remark in https://github.com/haskell/primitive/issues/211#issuecomment-512601248, which is a better definition. i'm happy to paste that into primitive master / next release (unless a better design is proposed)

**Comment by chessai** [comment]
okay, see haskell-primitive/primitive-convenience@15f302e

**Comment by ekmett** [comment]
Looks good to me!
