### ISSUE TITLE
Deprecate touch and introduce with

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#216]
Per [trac issue 14346](https://ghc.haskell.org/trac/ghc/ticket/14346), `touch#` is an unwieldy primop. In a [commit to GHC](https://git.haskell.org/ghc.git/commitdiff/56590db07a776ce81eb89d4a4d86bd0f953fb44e), @bgamari writes:

> As noted in #14346, touch# may be optimized away when the simplifier can see
that the continuation passed to allocaBytes will not return. Marking CPS-style
functions with NOINLINE ensures that the simplier can't draw any unsound
conclusions.
> Ultimately the right solution here will be to do away with touch# and instead
introduce a scoped primitive as is suggested in [#14375](https://ghc.haskell.org/trac/ghc/ticket/14375).

Fortunately, the `with#` primop is coming in GHC 8.8. I think that `Control.Monad.Primitive` should export a `with` function that maintains backwards compatibility in a way the resembles what @treeowl [suggested for a `with#` shim](https://ghc.haskell.org/trac/ghc/ticket/14375#comment:17). On older GHCs, it would use `NOINLINE` pragma and `touch#`. On GHC 8.8+, it would use `with#`. The type would be:

    with :: (PrimBase m) => a -> m b -> m b
    withUnlifted :: (PrimBase m, PrimUnlifted a) => a -> m b -> m b

The second one would prevent an unneeded boxing when a pinned `MutableByteArray` was passed as the first argument. I'm assuming that `with#` accept lifted and unlifted arguments just like `touch#` does. And we should deprecate `touch` since `with` is better.

**Comment by cartazio** [comment]
We can totally add with ... but there’s too much code out there depending
on touch for us to deprecate it. We can and should definitely move to with
once it’s stabilized for internals of primitive. At least for now.

**Comment by cartazio** [comment]
And add with to pritmive. And add documentation

I’ll do that later today or this weekend

**Comment by treeowl** [comment]
In its first version, `with#` may not be the most efficient. When it applies safely, `touch#` may remain better for a while. I haven't checked how that plays in `primitive` internals. I suspect we're likely to need the safety of `with`, but there could be places where we can get away with `touch`.

**Comment by cartazio** [comment]
Yeah.

I fully support us making sure internals of primitive are safe and
performant wrt our memory liveness.

**Comment by cartazio** [comment]
closing this ticket, and lets track the status of the concrete action times in issue #221.

(the current ghc UX for deprecated but supported operations operations isn't great, and theres a lot of old code out there that uses touch which will definitely break with the removal of touch)
