### ISSUE TITLE
Add PrimMonad instances for CPS's WriterT and RWST

### ISSUE THREAD

**Issue by axman6** [haskell/primitive#226]
Since `transformers-0.5.6.0`, there are now CPS'd implementations of `WriterT` and `RWST`; it would be great to have `PrimMonad` instances for these. We're currently using a module of orphan instances for the implementations from `writer-cps-transformers`, but being able to use the `transformers` versions would be great.

**Comment by cartazio** [comment]
Huh. @hvr and I will look over it.  There’s a bunch of other things we want
to review leading up to our next primitive release.

Is this critical for any libraries you’re using atm? Or just a wart in one
spot?

**Comment by axman6** [comment]
Just a wart we've got a fix for, it's mostly useful for consistency.
