### ISSUE TITLE
Endianness of `Prim` word instances

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/primitive#230]
Hi, perhaps not the place to ask this question but -

Is the endianness of the Prim Int/Word 16/32/64 documented anywhere? And is it stable across different architectures? It's little endian on my machine.

**Comment by cartazio** [comment]
It’s platform dependent.  Whatever ghc supports / does for unlifted base
types that correspond to in register values, that’s what prim does.

The way I frame it is: primitive type classes / interfaces are first and
foremost about choices that aid and abet the vector package being as great
as possible from a user and maintainer perspective as a library for writing
fast in memory vector / array calculations.
