### ISSUE TITLE
how can i install it

### ISSUE THREAD

**Issue by Alymostafa** [haskell/primitive#232]
i can't install it using cabal i download it from hackage but I can't setup it

**Comment by andrewthad** [comment]
This question isn't specific to `primitive`. If you are just trying to figure out how to use the cabal package manager or how to use GHC, you can find help on the haskell-cafe@haskell.org mailing list. You will need to be more specific with your question though. Provide the commands you have run and what you're seeing on stdout, and you'll be more likely to get helpful responses. Off the top of my head, I would guess that you may need to do any one of these commands (but not all of them):

- `cabal install primitive`
- `cabal new-install primitive`
- `cabal unpack primitive && cd primitive && cabal new-build`

Or just listing `primitive` as a dependency in your own project's cabal file and letting cabal sort it out when you run `cabal new-build`. Again, you'll have to provide more information and ask on the appropriate channels.
