### ISSUE TITLE
UnliftedArray is unsound

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#238]
[GHC issue #16650](https://gitlab.haskell.org/ghc/ghc/issues/16650) includes an example of how `primitive`'s implementation of `UnliftedArray` relies on a use of `unsafeCoerce#` that GHC does not actually support. I'm not really sure how to fix this. Putting a bunch of `NOINLINE` pragmas on the `UnliftedArray` stuff will probably work, but a good solution will not be available until I implement the [Pointer Rep Proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0045-pointer-rep.rst).

**Comment by cartazio** [comment]
Good to know.

With that In mind as added issues, I’m inclined to split out unlifted array
tooling for 0.7 as it’s own package so issues around breaking that don’t go
back into core primitive.

Making/ensuring  core primitive trust worthy is pretty valuable / high
impact.  So it sounds like I’ll have to prep O.7 post haste

I imagine we’re talking really unsound kind system issues ?  I’ll take a
look at the ticket.

**Comment by andrewthad** [comment]
I am similarly inclined to have `UnliftedArray` live in a different package. This issue cannot be repaired in user space without massive performance penalties, and one of the goals (to my understanding at least) of `primitive` is that performance should be predictable. Additionally, variants of `TVar`, `MVar`, `SmallArray`, `MutVar`, `StableName`, and `Weak` accepting an unlifted boxed payload will be possible in GHC 8.10 or GHC 8.12, and it would make sense to have them all together in a less-backwards-compatible `primitive-unlifted` package rather than trying to shim them out with a bunch of `unsafeCoerce#` in `primitive`.

**Comment by cartazio** [comment]
Agreed!

**Comment by andrewthad** [comment]
This has been removed from `primitive`. I have a more sound alternative implementation `primitive-unlifted`.
