### ISSUE TITLE
Missing operations: `cloneMutablePrimArray` and `clonePrimArray`

### ISSUE THREAD

**Issue by ekmett** [haskell/primitive#239]
`Data.Primitive.PrimArray` basically apes the API of `Data.Primitive.Array` on top of `Data.Primitive.ByteArray`. 

These operations are offered by `Array`/`MutableArray` but not `PrimArray` at present.

**Comment by chessai** [comment]
There are a large number of module inconsistencies like this, which should
be enumerated and eliminated.

In the meantime, until someone prepares a PR, either one of defining them
on your own/using the [`contiguous`](
http://hackage.haskell.org/package/contiguous-0.4.0.1/docs/Data-Primitive-Contiguous.html)
package should work.

**Comment by ekmett** [comment]
I'm just enumerating them as I find them pointwise as simple issues. This isn't blocking me so much as making an API of something i'm writing downstream equally inconsistent ;)

**Comment by andrewthad** [comment]
This has been resolved.
