### ISSUE TITLE
add instances for ST.Lazy

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#24]
someone asked this on haskell-cafe, and its a reasonable request unless theres a good reason to the contrary

**Comment by RyanGlScott** [comment]
I think the thing blocking this from happening is that, to my knowledge, `base` doesn't export the constructor for lazy `ST`, making it impossible to implement `primitive`.

**Comment by Zemyla** [comment]
However, it does export `strictToLazyST`, which is pretty much the exact same thing. It also exports `lazyToStrictST`, so it can also be an instance of `PrimBase`.

**Comment by cartazio** [comment]
There's some pretty deep bugs in how ghc currently handles /
implements  lazy st

Some care may be needed

**Comment by christiaanb** [comment]
I'd like this feature so that I can use functions from the `vector` package in the lazy ST monad: http://hackage.haskell.org/package/vector-0.11.0.0/docs/Data-Vector-Mutable.html

**Comment by treeowl** [comment]
I don't think the fact that `ST` is not exported causes fundamental difficulties. I've written a [patch](https://phabricator.haskell.org/D3038) that I believe resolves the concurrency bug. Writing that made me very glad that the constructor is not exported: I was able to rely on the fact that no one outside the module could get their hands on a `(State s, r)` result pair (unless they used `unsafeCoerce` and entered unsupported territory). I suspect @Zemyla has the right idea, but if there's some purpose for which that's insufficient I can try to help. All that said, I'm not sure lazy `ST` really should be a `PrimMonad`. Its semantics are pretty different even though it's handling similar things to `IO` and `ST`. It would probably be clearer for the user to make the conversions explicitly.

**Comment by cartazio** [comment]
....the difference being that we have to convert from a lazy stateToken to
a strict one?

**Comment by treeowl** [comment]
Well, I guess it wouldn't be *bad* to have the instance, though I'm not
sure how useful it would be in practice. In any case, it's pretty simple:

instance Primitive (ST s) where
  PrimState (ST s) = s
  primitive = strictToLazyST . primitive

instance PrimBase (ST s) where
  internal = internal . lazyToStrictST

I don't think digging into the internals would give you anything better.

**Comment by Avi-D-coder** [comment]
What is blocking this?

**Comment by chessai** [comment]
I don't know if anything is blocking this, per se.

Most of the time when I am working in some `PrimMonad`, I want things (my
work on arrays/mutable arrays) to be strict.

I'm not opposed to having the instance, since I generally believe in having
more instances than not. But, does anyone even use Lazy ST? I was under the
impression it was a wart.

**Comment by christiaanb** [comment]
I used to use it in my Clash circuit descriptions to represent large memories, something along the line of:

```haskell
memory :: Stream (ArrayUpdate a) -> Stream ArrayIndex -> LazyST s (Stream a)
```
(or `Stream` and `LazyST s` transposed... I forgot). Where I'd use a mutable array to implement the actual memory, thinking that it'd be faster than an immutable array. I needed LazyST because the stream of ArrayUpdates might depend on the values coming out of the `memory` in a tying-the-knot type of recursive description. Anyhow, even after much trying, it had space-leaks I simply couldn't fix, and I switched to immutable arrays ever since; it turned out to be faster as well.

**Comment by chessai** [comment]
Ah, I was replying via email and didn't see the much earlier messages.

I agree with David Feuer here, I'm not really opposed to the instance existing, but I think its its usefulness is questionable.

@Avi-D-coder you could always send a PR?

**Comment by Avi-D-coder** [comment]
I Just used `.Lazy` and treeowl's instance to bring me from over a 8G (leaking) to 9M (tight loop). There are definitely a few cases where it's needed.

**Comment by cartazio** [comment]
Thanks for tickling this ticket.  I’ll have a poke

**Comment by chessai** [comment]
@Avi-D-coder can you show me the code? I'm not doubtful, just curious.

**Comment by Avi-D-coder** [comment]
@chessai  I'm still working on it, I'll post it, when I get a chance. I think the combination of nested `mapM` and strict `ST` was forcing the computation into memory. I'm hoping there's a better way, but I have not found one without `unsafePerformIO`.

**Comment by Avi-D-coder** [comment]
@cartazio I used treeowl's code, just to get it done. If you think there's a better way, I'll close my PR.

**Comment by Avi-D-coder** [comment]
@chessai 
Any `mapM` or `sequence` over a large lazy list `[ST s a]` forces all the computations list to manifest in memory. While I was able to break the computation into many smaller `runST` computations, that still performed faster despite performing extra initialization per each `ST`, if all of computations are interdependent `ST.Lazy` is required.
