### ISSUE TITLE
Missing instances: Eq (MutablePrimArray s a), Eq (MutableByteArray s)

### ISSUE THREAD

**Issue by ekmett** [haskell/primitive#240]
Both have obvious definitions in terms of

```
instance Eq (MutablePrimArray s a) where
  (==) = sameMutablePrimArray

instance Eq (MutableByteArray s) where
  (==) = sameMutableByteArray
```

and no other valid possible interpretation. 

The status quo makes them act as bad citizens in larger types with derived equality.

**Comment by andrewthad** [comment]
I've put up a PR that adds these instances.

**Comment by andrewthad** [comment]
This has been merged. Closing.
