### ISSUE TITLE
CI strangeness involving test suites and benchmarks

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/primitive#243]
I recently set out to regenerate the `haskell-ci`-generated `.travis.yml` in this repo to address the issue reported [here](https://github.com/haskell/primitive/pull/241#issuecomment-495928260). But I ultimately stopped because several things aren't quite right with the way the test suites and benchmarks are configured, and I don't know how to proceed.

* For starters, the `cabal.project` no longer contains the `test` or `bench` directories. This appears to have changed in commit 5c1dc71b8fee9320f19e87ca2e5c64afaaabc1c4 for unexplained reasons.
* Moreover, neither the tests nor the benchmarks seem to be built on Travis anymore, since the current `.travis.yml` file doesn't mention them! See [this commit](https://github.com/haskell/primitive/commit/d0cfe56de9be69b8616c56cbfdb36d401fe0ec5d#diff-354f30a63fb0907d4ad57269548329e3), where they seemingly disappeared.
* Actually, my previous bullet point was slightly inaccurate. When I looked at the Travis output of a recent run, it appears that the tests _are_ being built. How is this possible? It turns out that [this commit](https://github.com/haskell/primitive/commit/6bdcc5fb7fe07c71989e22beb0f87ba14b31875a) migrated the test suite `.cabal` file from the `test/` directory directly into `primitive.cabal` itself.

  But wait, there's more. That commit _checks in the entire source code of `quickcheck-classes`_... what!? For the life of me, I cannot figure out why this was done, and the commit message does not include an explanation.

@cartazio, you authored all of the commits I mentioned above. What is going on here? The current situation is rather baffling.

**Comment by cartazio** [comment]
The other setup forced longer local builds for local dev testing.  And the
prim laws were maintained in qc-classes.

This made every build way longer, meant the law testing for prim specific
stuff was elsewhere, and meant cabal test was useless.

Andrew is doing a release of qc classes base soon then I’ll switch to
depending on that.

Also I want to have the benchmark executable stuff split between the
reference codes we compare and the measurement harness so that extra bit of
rebuilding vector etc is only for doing the measurements, but so that we
still make sure we keep the examples building for comparison.

There’s probably some other stuff.

Also some of the laws I commented out in the prim module because type
inference failures happened that I didn’t understand.

**Comment by RyanGlScott** [comment]
> The other setup forced longer local builds for local dev testing.

I'm unclear on what you mean by this. The tests and benchmarks are disabled unless you specifically enable them with the `--enable-tests` or `--enable-benchmarks` flags, respectively, so there shouldn't be any way to trigger local builds of packages that depend on `primitive` itself (like `quickcheck-classes`) unless you opt in to it.

> And the prim laws were maintained in qc-classes.

OK? I'm not sure you're getting at here. Was there a specific bug in `quickcheck-classes` that you had to work around? If so, I'd much prefer using a `source-repository-package` of a fork of `quickcheck-classes` instead of checking in the source code directly, since doing the latter means that that package's files are going to forever be a part of the `git` history, even after we un-vendor it.

> and meant cabal test was useless.

What? That shouldn't have been the case. If it was, something was horribly wrong, and a ticket should be opened about it.

> Also I want to have the benchmark executable stuff split between the reference codes we compare and the measurement harness so that extra bit of rebuilding vector etc is only for doing the measurements, but so that we still make sure we keep the examples building for comparison.

Fair enough. Is there a ticket open about this? I'm loathe to not build the benchmark code at all in the interim, since it means that the code can bitrot.

> Also some of the laws I commented out in the prim module because type inference failures happened that I didn’t understand.

Again, is there a ticket about this? I can't really figure out what is going on from this description alone.

**Comment by cartazio** [comment]
I’ll sit down and look at stuff after I’m back from travel this weekend
