### ISSUE TITLE
Missing copyPtrToMutablePrimArray and copyPtrToMutableByteArray

### ISSUE THREAD

**Issue by ekmett** [haskell/primitive#244]
We have `copyMutablePrimArrayToPtr` and `copyMutableByteArrayToAddr` but not the converse operations, which also have operations in GHC.Prim.

**Comment by cartazio** [comment]
Good catch. I knew there were a few things missing when I cut 0.7, but I
wanted to just get it out the door.  I’ll cut a release soon

**Comment by ekmett** [comment]
Nevermind. This one is buried in `Data.Primitive.Ptr` which I somehow missed.
