### ISSUE TITLE
Rename copyByteArrayToAddr to copyByteArrayToPtr

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#245]
The names of the functions in `Data.Primitive.ByteArray` that reference `Addr` are no longer accurate. It would be better to use `Ptr` in the name. One possible strategy would be to add the new names in the next minor release and soft deprecate the names mentioning `Addr` (`primitive-0.7.1.0`), and then remove the names that mention `Addr` in the next major release (`primitive-0.8.0.0`).

**Comment by cartazio** [comment]
agreed, i left them in for 0.7 so that it wasn't a hard break, but AGREED.
100%

**Comment by andrewthad** [comment]
This function was added some time ago. Closing.
