### ISSUE TITLE
Missing Instances for Array

### ISSUE THREAD

**Issue by ekmett** [haskell/primitive#25]
Array carries around its length (since 7.2?), so it is capable of being an instance of many well known abstractions:

`Read`, `Show`, `Eq`, `Ord`, `Data`, `Typeable`, `Functor`, `Foldable`, `Traversable`, and `IsList` all come to mind. For that matter so do `Applicative`, `Alternative`, `Monad`, `MonadPlus` with concatenative semantics, `MonadZip`, `MonadFix`, etc.

**Comment by dolio** [comment]
These are now implemented.
