### ISSUE TITLE
Add ioToPrim, stToPrim

### ISSUE THREAD

**Issue by ekmett** [haskell/primitive#26]
There is no nice way to lift an `ST s` action into `PrimMonad` without a big type signature on `primToPrim`. We can go the other way, `primToST`, `primToIO` (with `PrimBase`) but there is no `ioToPrim` or `stToPrim`, able to be used on any `PrimMonad`.

**Comment by andrewthad** [comment]
I would also like these functions.

**Comment by ekmett** [comment]
Yay!
