### ISSUE TITLE
Question: Profiling issue: Why would a profiled build fail to link with missing references to primitive?

### ISSUE THREAD

**Issue by adetokunbo** [haskell/primitive#260]
Sorry in advance! This is probably the wrong place to ask this question, since it's not a bug or feature request, but really a question about linking/profiling.

However,  I'm asking about it here in the hope that any of the maintainers of the primitive package may have come across this issue before.

- I have an exe (not open source) that builds and links ok _without_ profiling enabled
  Build environment:
    OS: Ubuntu 18.04.4 LTS
    Build tools: Cabal / Nixpkgs
    Cabal-install version:  2.2.0.0
    GHC: 8.4.5

- I  enabled profiling by adding `profiling: True` to  the project's `cabal.project.local`
- I have also added some profiling flags for building the exe: `-threaded -fprof-auto "with-rtsopts=-N -p"`

With the profiling options, the build of exe fails while linking; I've include some of the link errors below.  Both my library, and its dependencies have unsatisfied references to functions in Data.Primitive.Array.

On removing the profiling options, everything builds ok.  Why might this happen?

```
/home/my-user/Developer/repos/my-frontend/dist-newstyle/build/x86_64-linux/ghc-8.4.3/my-library-0.0.1.0/build/libHSmy-library-0.9.1.0-inplace_p.a(Types.p_o): In function `s1s7k_info':
/run/user/1000/ghc1780_0/ghc_106.p_o:(.text+0x1f61c): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_marrayzh_CnSN_cc'
/run/user/1000/ghc1780_0/ghc_106.p_o:(.text+0x1f661): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_marrayzh_CnSN_cc'
/run/user/1000/ghc1780_0/ghc_106.p_o:(.text+0x1f6de): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_marrayzh_CnSN_cc'
...

/nix/store/68y3bqhn36vjk3b3jc1gs1jixqdbglfi-resource-pool-0.2.3.2/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/resource-pool-0.2.3.2-L9dsKMZPIEp4dQkidYf2X6/libHSresource-pool-0.2.3.2-L9dsKMZPIEp4dQkidYf2X6_p.a(Pool.p_o):(.text.sfs5_info+0x472): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_arrayzh_CnSO_cc'
/nix/store/68y3bqhn36vjk3b3jc1gs1jixqdbglfi-resource-pool-0.2.3.2/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/resource-pool-0.2.3.2-L9dsKMZPIEp4dQkidYf2X6/libHSresource-pool-0.2.3.2-L9dsKMZPIEp4dQkidYf2X6_p.a(Pool.p_o):(.text.sfwQ_info+0x229): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_marrayzh_CnSN_cc'

...

/nix/store/rjrn6bhyvmays3v2wycqqpkb7lkrkqmf-postgresql-simple-0.5.4.0/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/postgresql-simple-0.5.4.0-FbcMieVxyhU75rpKDfSbCw/libHSpostgresql-simple-0.5.4.0-FbcMieVxyhU75rpKDfSbCw_p.a(TypeInfo.p_o):(.text.r1zRb_info+0x144): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_marrayzh_CnSN_cc'
/nix/store/rjrn6bhyvmays3v2wycqqpkb7lkrkqmf-postgresql-simple-0.5.4.0/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/postgresql-simple-0.5.4.0-FbcMieVxyhU75rpKDfSbCw/libHSpostgresql-simple-0.5.4.0-FbcMieVxyhU75rpKDfSbCw_p.a(TypeInfo.p_o):(.text.r1zRb_info+0x5db): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_marrayzh_CnSN_cc'
/nix/store/rjrn6bhyvmays3v2wycqqpkb7lkrkqmf-postgresql-simple-0.5.4.0/lib/ghc-8.4.3/x86_64-linux-ghc-8.4.3/postgresql-simple-0.5.4.0-FbcMieVxyhU75rpKDfSbCw/libHSpostgresql-simple-0.5.4.0-FbcMieVxyhU75rpKDfSbCw_p.a(Types.p_o):(.text.stoY_info+0xf3): undefined reference to `primitivezm0zi6zi3zi0zmDaZZpcxwJp2TGn8ITSgfI4C_DataziPrimitiveziArray_arrayzh_CnSO_cc'
```

**Comment by cartazio** [comment]
This is absolutely a reasonable question

I’d suggest first seeing if this problem still happens with cabal install
version 3.

Could you try that?  The Hvr ppas might be an easy way to install a newer
version of cabal-install.

**Comment by adetokunbo** [comment]
@cartazio Thanks for the suggestion!

I just tried this, but it still fails as above...

- added cabal-3.0 as follows:

  ```
  sudo add-apt-repository ppa:hvr/ghc
  sudo apt-get update
  sudo apt-get install -y cabal-install-3.0
  ```
- cleaned dist-newstyle. `rm -fR dist-newstyle/`
- re-ran the build  using the newer cabal version `/opt/cabal/3.0/bin/cabal new-build my-package:my-exe`

The build failed to link with similar errors

**Comment by andrewthad** [comment]
I'm am a little wary of the combination of `cabal new-build` for a profiling build and nix (both of these tools manage dependencies). nix can be made to perform a profiling build with `nix-build`, and it will get all the profiling builds of dependencies in place for you. You may want to try that instead.

**Comment by cartazio** [comment]
Ohhh. This is via nix packaging rather than nix style cabal on unbuntu?
Yeah this sounds like Andrews martins suggestion is the way to roll.  Def a
nix pkgs ux and debugging issue rather than primitive lib ;)

**Comment by cartazio** [comment]
Yeah this sort of linker error means the modules aren’t there.  Which
matches up with nixos packaging managing your builds.  As Andrew indicated,
you’ll need to have the nix tooling give you the profiled flavor of your
 deps

**Comment by cartazio** [comment]
Closing 
This is definitely a build tooling Issue. Merry debugging :)

**Comment by adetokunbo** [comment]
> Yeah this sort of linker error means the modules aren’t there

@cartazio @andrewthad Thanks for the advice!  This was correct.  I looked more closely at my project's nix configuration, and noticed a problem that meant this was the case.  

Specifically, I had a dependency component specified as an exe (in the nix configuration), but exe being profiled was depending on it as as if it was a library.  Running `nix-build` made this clear.
