### ISSUE TITLE
NFData instance for ByteArray

### ISSUE THREAD

**Issue by Boarders** [haskell/primitive#267]
For the purposes of using benchmarking with criterion it would be nice if `ByteArray` had an `NFData` instance (so that one can use the [env function](https://hackage.haskell.org/package/criterion-1.5.6.2/docs/Criterion-Main.html#v:env)). Is there a fundamental reason why this doesn't exist?

**Comment by treeowl** [comment]
No, this seems eminently reasonable.

**Comment by cartazio** [comment]
Agreed.

**Comment by Boarders** [comment]
Added a PR [here](https://github.com/haskell/primitive/pull/270) but it is a bit naive.
