### ISSUE TITLE
Release 0.7.1.0 on 2020-06-19

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#284]
@haskell/core-libraries-committee 

I am planning to release a new version of `primitive` on June 19, 2020. No breaking changes, just a lot more functions. There are many issues and several PRs on `primitive` that have not seen any activity in a while. If anyone is interested in getting any additional changes in before the next release, put up any PRs and ping the maintainers for review. Thank you.

**Comment by lehins** [comment]
@andrewthad I believe #286 is serious enough bug that should be fixed for this release

**Comment by andrewthad** [comment]
Release candidate is at https://hackage.haskell.org/package/primitive-0.7.1.0/candidate and PR bumping version is at https://github.com/haskell/primitive/pull/290

**Comment by chessai** [comment]
@lehins can you please review the package candidate, and make sure that vector is fine with it?

**Comment by lehins** [comment]
@chessai I reviewed the changes in 0.7.1 RC and there aren't any breaking changes, just addition and fixes, so none of them affect vector in any way really. Just as a sanity check vector test suite does pass with primitive-0.7.1.0 :+1: from me.

**Comment by chessai** [comment]
@lehins awesome, thank you very much. @haskell/core-libraries-committee @treeowl does anyone see anything missing or any tickets that may need resolving?

**Comment by andrewthad** [comment]
This has been released.
