### ISSUE TITLE
drop support for older GHCs in 0.8 release

### ISSUE THREAD

**Issue by chessai** [haskell/primitive#292]
Recently, both vector and random have dropped support for anything pre-7.10. I think this is reasonable, since 7.0-7.8 are really old, and impose some annoying maintenance burdens.

**Comment by andrewthad** [comment]
We don't have to wait for 0.8 for this. The 0.7.1.0 release is about to be uploaded (I should do that today), but I'd be fine with dropping support for old GHCs even at the 0.7.2.0 release.

**Comment by chessai** [comment]
Ah, you're right. I always have to refer back to the PVP to check, but this doesn't require a majour version bump.
