### ISSUE TITLE
Show instance of bytearray suppresses leading zeroes in octets

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#306]
Currently, the `Show` instance of `ByteArray` gives this:

    [0xb, 0x1f, 0x5]

instead of this:

    [0x0b, 0x1f, 0x05]

I find the latter preferably. I'm going to leave this open to solicit feedback.

**Comment by chessai** [comment]
+1 to change

**Comment by treeowl** [comment]
Yes, I think you're right. Both are correct, but filling out the last byte
will give more readable, more easily aligned output. +1

**Comment by andrewthad** [comment]
Alright, I'm going to go ahead with this. Any thoughts on whether or not to do a major version bump for this? Technically, it's a breaking change, but I'm not aware of anything outside of test suites that even *uses* the `Show` instance of `ByteArray`.

**Comment by andrewthad** [comment]
This will be resolved by https://github.com/haskell/primitive/pull/309. Any comments there would be appreciated.
