### ISSUE TITLE
`thawPrimArray`/`thawByteArray` missing

### ISSUE THREAD

**Issue by konsumlamm** [haskell/primitive#307]
I noticed that `Data.Primitive.PrimArray` has `freezePrimArray`, `unsafeFreezePrimArray` and `unsafeThawPrimArray`, but no `thawPrimArray`. Similarly, `Data.Primitive.ByteArray` has no `freezeByteArray`. Since this isn't mentioned anywhere, I assume that's an oversight. It could be easily implemented in a similar fashion to `freezePrimArray`/`freezeByteArray`.

**Comment by andrewthad** [comment]
I think thaw could be implemented as new + copy + unsafeFreeze. This is an oversight. If you PR it, I will accept the PR.
