### ISSUE TITLE
Compatibility with transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [haskell/primitive#310]
https://hackage.haskell.org/package/transformers-0.6.0.0/changelog

Could you upload a compatible release or make a Hackage revision?

**Comment by chessai** [comment]
@andrewthad Do you have time to do this today? If not, I can get to it this weekend.

**Comment by andrewthad** [comment]
I've put up a PR that resolves this. I'll merge after CI completes.

**Comment by andrewthad** [comment]
Resolved by https://github.com/haskell/primitive/pull/314. This has not yet been released to hackage. If I haven't released this by Friday, ping me.

**Comment by sjakobi** [comment]
> Resolved by #314. This has not yet been released to hackage. If I haven't released this by Friday, ping me.

Ping @andrewthad! :)

**Comment by phadej** [comment]
ping @andrewthad

**Comment by andrewthad** [comment]
After https://github.com/haskell/primitive/pull/315 completes, I'll release 0.7.2.0.

**Comment by sjakobi** [comment]
Thank you, @andrewthad! :)
