### ISSUE TITLE
Add template-haskell Lift instances

### ISSUE THREAD

**Issue by phadej** [haskell/primitive#331]

**Comment by treeowl** [comment]
Good idea. For `PrimArray`, we should be sure to end up with `Addr#` literals.

**Comment by phadej** [comment]
Except there is no efficient way to construct `ByteArray#` from `Addr#`, ... but it would be still better then reinventing the wheel.

**Comment by treeowl** [comment]
@phadej , dagnabbit! The best we can do is use a single GHC primop to perform the copy at runtime (`copyAddrToByteArray#`, IIRC). Has anyone formally proposed `Array`, `SmallArray`, and `ByteArray` literals yet? If not, do you think you could do so?

**Comment by phadej** [comment]
Formally no. There is issue about them. https://gitlab.haskell.org/ghc/ghc/-/issues/16944

And proposals  https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2971
