### ISSUE TITLE
`primitive` fails to compile for 7.10

### ISSUE THREAD

**Issue by konsumlamm** [haskell/primitive#337]
#332 introduced `Lfit` instances. However, this uses the `TemplateHaskellQuotes` extension, which is only available since GHC 8.0. There are several options how to resolve this:

* drop 7.10 support
* use the `TemplateHaskell` extension for 7.10
* don't define the `Lift` instances for 7.10

EDIT: The `Lift` instances also use `emptyArray#`/`emptySmallArray#`, which isn't available either for GHC 7.10.

**Comment by andrewthad** [comment]
I'm fine with just dropping support for 7.10.
