### ISSUE TITLE
Add PrimRef

### ISSUE THREAD

**Issue by oberblastmeister** [haskell/primitive#342]
`PrimRef` would be a wrapper around `MutableByteArray`. I am interested in making a pr if this makes sense.

**Comment by chessai** [comment]
can you explain what the motivation is, or what the api for this would be?

**Comment by oberblastmeister** [comment]
The api would be like `MutVar` but for types that have `Prim` instances.

**Comment by konsumlamm** [comment]
Note that this already exists in the [prim-ref](https://hackage.haskell.org/package/prim-ref) package. I also implemented something like this [here](https://github.com/konsumlamm/rrb-vector/blob/master/src/Data/RRBVector/Internal/IntRef.hs).

In my benchmarks, I found it to be considerably faster than a `MutVar`/`STRef`, so I think this would be worth considering.

**Comment by lehins** [comment]
Some more prior art: [`pvar`](https://hackage.haskell.org/package/pvar) and [`mutable-containers`](https://hackage.haskell.org/package/mutable-containers)

I also think it would be useful addition to the `primitive` package.

**Comment by chessai** [comment]
I am in favour

**Comment by andrewthad** [comment]
Completed in https://github.com/haskell/primitive/pull/343
