### ISSUE TITLE
'copyByteArrayToPtr' uses number of bytes instead of number of elements

### ISSUE THREAD

**Issue by mozhewen** [haskell/primitive#345]
https://github.com/haskell/primitive/blob/b0c5294fe6351ea9c649ed2522a61362b31fa79a/Data/Primitive/ByteArray.hs#L455-L466
According to the documentation, 'sz' should be the "number of elements", while 'copyByteArrayToAddr#' wants  "number of bytes". Line 464 should be something like `... ((unI# sz) *# siz#) ...`. This same issue applies to 'copyMutableByteArrayToPtr'.

**Comment by andrewthad** [comment]
yeah, that's really bad. I'd take a PR fixing this
