### ISSUE TITLE
Release for GHC 9.6?

### ISSUE THREAD

**Issue by Bodigrim** [haskell/primitive#364]
Or alternatively revise existing `primitive-0.7.4.0` to allow `base-4.18`.

**Comment by andrewthad** [comment]
If you confirm that 0.7.4.0 builds with GHC 9.6, I’ll make a hackage revision.

**Comment by andrewthad** [comment]
If you confirm that 0.7.4.0 builds with GHC 9.6, I’ll make a hackage revision.

**Comment by Bodigrim** [comment]
Confirmed.

**Comment by andrewthad** [comment]
I've adjusted the bound on hackage. Do you know if it's possible yet to target GHC 9.6 with CI?

**Comment by andrewthad** [comment]
`primitive-0.8.0.0`, which supports GHC 9.6, has been released to hackage. Closing.
