### ISSUE TITLE
Expose size information at the type level

### ISSUE THREAD

**Issue by oberblastmeister** [haskell/primitive#374]
Add a type family
```haskell
type family SizeOf (a :: Type) :: Nat
```
This is useful to make coercions between `PrimArray` easier. For example, we could have a function
```haskell
coercePrimArray :: (SizeOf a ~ SizeOf b) => PrimArray a -> PrimArray b
coercePrimArray = unsafeCoerce
```
Now, if all `Prim` instances are written correctly, `coercePrimArray` should be safe, which makes it better than doing `unsafeCoerce`.

**Comment by treeowl** [comment]
The size isn't necessarily all there is to say about it, is it?

**Comment by oberblastmeister** [comment]
What do you mean?

**Comment by treeowl** [comment]
Well, suppose I make a `Prim` instance for 31-bit integers. The size will still be 32 bits, but some representations may be invalid.

**Comment by andrewthad** [comment]
I'm not convinced this is a useful addition to the library. As @treeowl points out, the size alone is not enough to provide the kind of guarantee you are looking for. Plus, you already don't have to use `unsafeCoerce` to do what you are trying to do. You can tear open a `PrimArray` and reassign the phantom type with `case myArray of {PrimArray inner -> PrimArray inner}`.

**Comment by oberblastmeister** [comment]
This might not be that useful
