### ISSUE TITLE
Get rid of fromList in all Show instances

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#388]
I just noticed that `fromListN` is used in the `Show` instance for `SmallArray`. I'd like to get rid of this everywhere.

**Comment by chessai** [comment]
What do you intend to replace it with?

**Comment by treeowl** [comment]
I guess the other option is to expect someone copying and pasting the output to use `OverloadedLists`.

**Comment by andrewthad** [comment]
Yes, I had the `OverloadedLists` syntax in mind. This is what `vector` and `text` do (well, `text` assumes `OverloadedStrings`) and the result is nicer for the user. I have unit tests in the `http-interchange` library that uses `Show` and `pretty-show` to create an expected output. Here is [one of them](https://github.com/byteverse/http-interchange/blob/f371c897629ec08b3d61e771c4fbb4f8d934b969/golden/response/002.output):

```
Response
  { statusLine =
      StatusLine
        { versionMajor = 1
        , versionMinor = 1
        , statusCode = 400
        , statusReason = "Bad Request"
        }
  , headers =
      fromListN
        2
        [ Header { name = "Content-Type" , value = "application/json" }
        , Header { name = "Content-Length" , value = "100" }
        ]
  }
```

The way `headers` is rendered is needlessly tedious. If we change the `Show` instance, then it becomes more useful in this context.

**Comment by chessai** [comment]
SGTM
