### ISSUE TITLE
Drop support for GHC 8.0

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#393]
In https://github.com/haskell/primitive/pull/392 I'm working on variants of `touch` and `keepAlive` that work on an argument of an unlifted type. GHC 8.0 lacks a kind system rich enough to express this kind of this. I'm inclined to drop support for GHC 8.0 since it is rather old at this point. I'll give this a few days to see if any feels strongly about supporting GHC 8.0. Or maybe we could go ahead and drop support for everything before 8.6 if we really wanted to get rid of a bunch of CPP.

**Comment by konsumlamm** [comment]
https://hackage.haskell.org/package/base-4.9.0.0/docs/GHC-Exts.html#t:RuntimeRep
Looks like GHC 8.0 does support unlifted types, the `RuntimeRep` is just called `PtrRepUnlifted` instead of `UnliftedRep`.

**Comment by andrewthad** [comment]
Thanks. I had forgotten this was even available in 8.0. Closing since I've been able to make https://github.com/haskell/primitive/pull/392 build with 8.0.
