### ISSUE TITLE
primitive-0.8.0.0 works with GHC 9.8, ok to relax bounds?

### ISSUE THREAD

**Issue by andreasabel** [haskell/primitive#394]
Building (and tests) with GHC 9.8.1 alpha worked for me:
```
/primitive-0.8.0.0$ cabal test --allow-newer={base,deepseq}
```
Are you ok with relaxing the bounds on `base` and `deepseq` in `primitive-0.8.0.0`, @andrewthad ?

**Comment by andrewthad** [comment]
I've made a hackage revision. Let me know if this resolves the issue.
