### ISSUE TITLE
Missing createPrimArray and createByteArray

### ISSUE THREAD

**Issue by meooow25** [haskell/primitive#414]
`createArray` and `createSmallArray` are handy functions, but the equivalents seems to be missing for `PrimArray` and `ByteArray`.
https://github.com/haskell/primitive/blob/16421cac9842a9b8cb48eff33380d5ff45a83539/Data/Primitive/Array.hs#L353-L357
https://github.com/haskell/primitive/blob/16421cac9842a9b8cb48eff33380d5ff45a83539/Data/Primitive/SmallArray.hs#L477-L481

**Comment by andrewthad** [comment]
I agree. I would take a PR adding these.
