### ISSUE TITLE
Add ArrayArrays?

### ISSUE THREAD

**Issue by Zemyla** [haskell/primitive#46]
`ArrayArray#` and `MutableArrayArray#` have been around since ghc-prim 0.3.1.0, and adding `Data.Primitive.ArrayArray` should be fairly mechanical. Is there a reason why it hasn't been done? Is it because they're even less type-safe than other primitive operations?

**Comment by dolio** [comment]
I've been working on this, and I'm almost done, just adding the haddock.

I've wrapped them to be type safe, so you have arrays whose elements are particular other array types, not just the free-for-all in `ArrayArray#`.

**Comment by Zemyla** [comment]
Hmm. Well, we may need type-unsafe `ArrayArray`s though. Consider an unboxed `Vector` of `Vector`s. A `Vector (Vector Float)` might be implemented as an `ArrayArray` where the first element is a `ByteArray` containing all the lengths and offsets of the included `Vector`s, and the rest of the elements are `ByteArray`s containing the remaining vectors. Then a `Vector (Vector (Vector Float))` would have its first element be a `ByteArray` and its remaining elements be `ArrayArray`s.

For a less-contrived example, if you have a `MutableArrayArray` filled with `MutableByteArray`s, and you want to freeze it, you need to iterate through, take the `MutableByteArray`s out, freeze them, and put in the `ByteArray`s. Obviously, this means in the middle that some elements will be `ByteArray`s and some will be `MutableByteArray`s.

So there should be a typesafe interface, but there should also be a way to escape it.

**Comment by dolio** [comment]
Why should you be able to do these things? You can't do the latter with `Array`, either. And for the former, I don't think it's really necessary for the meta data of an unpacked vector-vector to be stored in the same array as the vectors' arrays.

The reason `ArrayArray#` is the way it is (that I know of) is that there is currently no separation of the unlifted pointer types, which are represented uniformly, from unboxed primitive types, which have no uniform representation, and thus no way to parameterize over that class of types. But people have been working on that, and in the future, there might just be a separate kind, and a primitive array that stores unlifted pointer types, so the underlying implementation would be type safe. If/when this happens, we'd be exposing something that throws away type safety that is already there.
