### ISSUE TITLE
use runRW# for unsafeInlineIO

### ISSUE THREAD

**Issue by AndrasKovacs** [haskell/primitive#53]
Use `runRW#` from [`GHC.Magic`](https://hackage.haskell.org/package/ghc-prim-0.5.0.0/docs/GHC-Magic.html) for `unsafeInlineIO`. Here's the relevant [discussion](https://ghc.haskell.org/trac/ghc/ticket/5916). Current `unsafeInlineIO` is unsafe to the point of unusability without `-fno-full-laziness`, while `runRW#` works fine with inlining.

**Comment by cartazio** [comment]
Hrmmm.  Interesting idea. 
Have you looked at the old bugs that bytestring had from unsafeInlineIo?

**Comment by AndrasKovacs** [comment]
I haven't. I am confident that `runRW#` is the proper solution. `unsafeDupablePerformIO` in `base-4.9` is also inlinable and defined with `runRW#`.

**Comment by bgamari** [comment]
Indeed this is the right solution.

**Comment by treeowl** [comment]
Unfortunately, my understanding is that code using `runRW#` (i.e., `unsafeDupablePerformIO`) still doesn't compile quite well enough for extreme bytestring performance hacking (I hear it costs 15% on some tests). I don't know why, but I don't think we should make the change. We can do something about documentation though.

**Comment by andrewthad** [comment]
In https://github.com/haskell/primitive/pull/281, I am discouraging use of `unsafePerformIO`, pointing users to `unsafeDupablePerformIO` instead.
