### ISSUE TITLE
Deprecate sizeofMutableByteArray

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#54]
This function is a thin wrapper around `sizeofMutableByteArray#` from `GHC.Prim`. The docs for this function carry the following deprecation warning:

> Return the size of the array in bytes. Note that this is deprecated as it is unsafe in the presence of concurrent resize operations on the same byte array. See getSizeofMutableByteArray.

I suggest that `primitive` deprecate its corresponding function and provide a `getSizeofMutableByteArray` function that wraps `getSizeofMutableByteArray#`. I'll put together the PR for this if someone approves it.

**Comment by dolio** [comment]
I think this sounds fine, although it's quite a paradigm shift. It probably doesn't make sense without wrapping resize, but you've offered to do that, too, so... :)

**Comment by treeowl** [comment]
Is there some other safe way of getting the size? If not, it seems to remain useful in situations where you know another thread won't be resizing the array.

**Comment by andrewthad** [comment]
I'm going to close this. Even though `sizeofMutableByteArray#` is deprecated in `ghc-prim`, I suspect that it will never be removed. As @treeowl points out, it is useful for people who know that they aren't going to be doing any resizing.

**Comment by treeowl** [comment]
I don't think we should `DEPRECATE` it, because the underlying primop isn't `DEPRECATED`. But we should provide a similar warning in the documentation.

**Comment by andrewthad** [comment]
I agree that we should add the warning.  Also, is it even possible to DEPRECATE a primop?

**Comment by andrewthad** [comment]
How about https://github.com/haskell/primitive/pull/129
