### ISSUE TITLE
Add resizeMutableByteArray

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#55]
It would be nice to have a wrapper for `resizeMutableByteArray#`. I will PR this if the maintainers agree.

**Comment by dolio** [comment]
I think this sounds fine. Might as well wrap `shrinkMutableByteArray#` as well, while you're at it.

**Comment by andrewthad** [comment]
It looks like the resize primitives weren't available until GHC 8.0. I can wrap them in CPP and remove the deprecation warning if that's an acceptable solution.

**Comment by dolio** [comment]
That sounds fine.

**Comment by andrewthad** [comment]
This has been implemented.
