### ISSUE TITLE
Documentation of Array copying functions

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#59]
The docs for `copyMutableByteArray` say:

> Copy a slice of a mutable byte array into another array. The two slices may not overlap.

However, the slices are actually allowed to overlap (at least, in GHC 8.0 they are). I assume that in older GHCs, this wasn't true. It would probably be worth mentioning that the limitation doesn't exist since GHC 7.X, where X is some value that I don't know.

**Comment by cartazio** [comment]
It may rather be a semantic requirement to allow changes to that behavior
to be allowed ? I.e. It's saying that the API doesn't guarantee that?

**Comment by andrewthad** [comment]
That makes sense. It seems very unlikely that the behavior could change in that way, but I can buy that it's at least possible.
