### ISSUE TITLE
Compilation with GHC HEAD

### ISSUE THREAD

**Issue by OlivierSohn** [haskell/primitive#69]
GHC version:
```
The Glorious Glasgow Haskell Compilation System, version 8.5.20171204 [d6fccfb2ba087abfdd4a68b13165e1312f9af022]
```
This is the error I see [when building my project with this GHC version:](https://travis-ci.org/OlivierSohn/hamazed/jobs/312954876)
```
Data/Primitive/Array.hs:531:10: error:
    • No instance for (Semigroup (Array a))
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid (Array a)’
    |
531 | instance Monoid (Array a) where
    |          ^^^^^^^^^^^^^^^^
```
The constraint I use in the .cabal is `base >= 4.8 && < 4.11`
Should I relax the constraint on base?

**Comment by hvr** [comment]
@OlivierSohn you may be interested in https://github.com/hvr/head.hackage if you're using GHC HEAD with Hackage

**Comment by RyanGlScott** [comment]
Yep. The version from Hackage doesn't support GHC HEAD at the moment. If you wish to build with GHC HEAD, build `primitive` from this repo, or use `head.hackage`.

**Comment by OlivierSohn** [comment]
Ok! Thank you.
