### ISSUE TITLE
Prim instance for Fingerprint

### ISSUE THREAD

**Issue by int-index** [haskell/primitive#70]
A fingerprint[1] is represented as a pair of `Word64` values. Would it be possible to have a `Prim` instance for it?

[1] https://hackage.haskell.org/package/base-4.10.1.0/docs/GHC-Fingerprint.html#t:Fingerprint

**Comment by andrewthad** [comment]
This should definitely be possible. Can a maintainer confirm this?

**Comment by cartazio** [comment]
The real question is: is Prim suppposed to only support native types that
have a ghc supported unlifted version or not?

**Comment by andrewthad** [comment]
One could argue that the unlifted version of `Fingerprint` is `(# Word64#, Word64# #)`. Maybe the more real question is whether or not there are only supposed be prim instances for things that fit in a single cpu register. Regardless, I think that @dolio will need to make a decision here.

**Comment by cartazio** [comment]
@andrewthad  thats not a built in type, you can always "unlift" the top layer of a type.

I mean: unlifted types that specifically have support in ghc-prim

there is no (#a,b#) which is supported as an unboxed array rep in ghc-prim, and the Prim type class is meant just for those.  Or at least that has been the historically focus.

if you want unboxed arrays of fingerprints, vector is a pretty good option.

monomorphic tuples in general have both "struct of array" and "array of structs", and primitive is the wrong package for that choice. Unboxed and Storable vectors make those respective choices.

for now i'm inclined to close this, @RyanGlScott @hvr @dolio thoughts?

**Comment by cartazio** [comment]
as an end user: you can easily make a new type wrapper to have your own prim instance in userland, but I dont think thats likely a good idea over unboxed or storable options (at least not without more info)

**Comment by cartazio** [comment]
(that is: more info about why Fingerprint should be added to prim/what the underlying used, or a going forward a new rubric for prim instances)
