### ISSUE TITLE
8.4/8.5 ish action items for support in a primitive release 

### ISSUE THREAD

**Issue by cartazio** [haskell/primitive#72]
Cc @ndmitchell :)

This will see some activity and stuff once the holiday season is over

**Comment by RyanGlScott** [comment]
One thing that we might consider doing is updating `.travis.yml` to include a GHC 8.4 build to give us some confidence that `primitive` does in fact build on 8.4 before cutting a release. I can do this today.

**Comment by RyanGlScott** [comment]
We should also update the `changelog` to mention:

* [ ] Add `Eq`, `Ord`, `Show`, and `IsList` instances for `ByteArray` (#62)
* [ ] Add `Semigroup` instances for `Array` and `SmallArray` (#65 and #66)

Neither of these are breaking changes, so a minor version bump should suffice.

**Comment by RyanGlScott** [comment]
At this point, my only remaining question is if there are any planned changes to GHC internals (such as `ghc-prim`) that are slated to land before the final GHC 8.4.1 release. Anything come to mind, @bgamari?

**Comment by bgamari** [comment]
Right, I don't anticipate there will be anything else.

**Comment by asr** [comment]
Blocking https://github.com/agda/agda/issues/2878.

**Comment by ndmitchell** [comment]
It's also blocking 9 of my packages.

**Comment by asr** [comment]
Also blocking the merge of https://github.com/byorgey/split/pull/3.

**Comment by bgamari** [comment]
For what it's worth, I do hope that -alpha3 will be the last pre-release with any substantial changes, so it would be good to start planning a path forward on this.

**Comment by hvr** [comment]
@bgamari Well, Dolio took a leap of faith and cut https://github.com/haskell/primitive/releases/tag/v0.6.3.0 ... let's hope the substantial changes in GHC 8.4.1-alpha2/3 don't invalidate that release ;-)
