### ISSUE TITLE
PrimUnlifted for MVar and TVar?

### ISSUE THREAD

**Issue by Zemyla** [haskell/primitive#75]
The `PrimUnlifted` typeclass seems to be about types that are wrappers around unboxed, garbage-collected pointers. `MVar` and `TVar` seem to fit the bill. Is there a reason why instances for them couldn't be written like so:

```haskell
import GHC.MVar (MVar(..))
import GHC.Conc (TVar(..))

instance PrimUnlifted (MVar a) where
  toArrayArray# (MVar mv#) = unsafeCoerce# mv#
  fromArrayArray# mv# = MVar (unsafeCoerce# mv)

instance PrimUnlifted (TVar a) where
  toArrayArray# (TVar tv#) = unsafeCoerce# tv#
  fromArrayArray# tv# = TVar (unsafeCoerce# tv)
```

Given that there's an instance for MutVar, it doesn't seem to be limited to the types that are shown in `GHC.Prim` as being usable with `ArrayArray`s. Is it because it doesn't deal with types that aren't directly defined in the `primitive` package, like `STRef`s and `IORef`s either? `STRef` and `IORef` seem to be subsumed by `MutVar`, but `MVar` and `TVar` don't have a substitute in `primitive`.

**Comment by andrewthad** [comment]
Anything of kind `TYPE 'UnliftedRep` is allowed in an `UnliftedArray`. In fact, I have a [ghc proposal to make this more clear](https://github.com/ghc-proposals/ghc-proposals/pull/112). The instances that you suggest are safe.

**Comment by andrewthad** [comment]
I've put up a PR for this.
