### ISSUE TITLE
Semigroup and Monoid instances for ByteArray

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#76]
Can I add `Semigroup` and `Monoid` instances for `ByteArray`?

**Comment by cartazio** [comment]
Concating or some operation on the bytes?

**Comment by andrewthad** [comment]
Sorry I didn't clarify that. Yes, concatenation. Zipping them together with conjunction or disjunction or xor or anything would require an infinitely long bytearray as `mempty`, so a `Monoid` instance wouldn't even be possible.

**Comment by cartazio** [comment]
Does it require an infinite mempty?

So there’s several legal semi group instances and only the concatenation
one is also a monoid

**Comment by andrewthad** [comment]
Yes, there are several possible semigroup instances. I think that concatenating is the most reasonable choice because:

- The `Monoid` instance for `Array` is defined with concatenation as `mappend`.
- No other semigroup instance gives rise to a `Monoid`.

**Comment by cartazio** [comment]
but ... is that the right way to support concatenation? It might be better
to provide a ByteArray Builder, so that repeated concat has the right
complexity, and provide the monoid instance for that instead, i think

**Comment by andrewthad** [comment]
But `primitive` isn't really an appropriate place for a builder. All other analogous types have this same concatenating `Monoid` instance: `Array`, `ByteString`, `Vector` (including primitive vectors). It's seldom a performant way to do things, but it's often convenient. Also, `mconcat` is useful here and can be overridden with something that gives much better complexity than its default implementation.

**Comment by cartazio** [comment]
perhaps you're right, what better complexity strategy do you have in mind?

**Comment by cartazio** [comment]
oh gotchs, good point

**Comment by andrewthad** [comment]
I've implemented this in https://github.com/haskell/primitive/pull/77

**Comment by cartazio** [comment]
@dolio @RyanGlScott @hvr  thoughts on this?

**Comment by RyanGlScott** [comment]
I'll comment on the pull request.

**Comment by RyanGlScott** [comment]
#77 has been merged.
