### ISSUE TITLE
Relax constraints for array indexing

### ISSUE THREAD

**Issue by treeowl** [haskell/primitive#78]
Currently,

```haskell
indexArrayM :: Monad m => Array a -> Int -> m a
indexSmallArrayM :: Monad m => SmallArray a -> Int -> m a
```

There is no obvious reason for the constraint to be `Monad` rather than `Applicative` (for GHC 7.10 and above); nothing is used but `return`.

**Comment by RyanGlScott** [comment]
That sounds reasonable to me. (And indeed, many `M`-suffixed methods in `base` have already had their constraint relaxed to `Applicative` on `base-4.8` or later.)

Care to offer a patch?
