### ISSUE TITLE
Copying between address and mutable byte array

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#80]
There are several functions in `GHC.Prim` for copying between an `Addr#` and a `MutableByteArray#`. For example:

    copyAddrToByteArray# :: Addr# -> MutableByteArray# s -> Int# -> Int# -> State# s -> State# s

I'd like to add wrappers for these to `primitive`. I'd document the minimum version of GHC required for these function to be available since I'm pretty sure these haven't been available forever, and `primitive` seems to be very backwards compatible. Would it be better to put them in `Data.Primitive.ByteArray` or `Data.Primitive.Addr`?

**Comment by cartazio** [comment]
Sounds reasonable.  Not sure which spot would be best.  Perhaps Ryan or Dan
have opinions

**Comment by andrewthad** [comment]
For reference:

    copyByteArrayToAddr# :: ByteArray# -> Int# -> Addr# -> Int# -> State# s -> State# s
    copyMutableByteArrayToAddr# :: MutableByteArray# s -> Int# -> Addr# -> Int# -> State# s -> State# s
    copyAddrToByteArray# :: Addr# -> MutableByteArray# s -> Int# -> Int# -> State# s -> State# s

I'm planning on putting the first two into `Data.Primitive.ByteArray` and the last one in `Data.Primitive.Addr`.
