### ISSUE TITLE
Supported versions of GHC?

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#83]
Is the oldest supported version of GHC specified anywhere. There's some CPP code in primitive that changes the implementation of functions if GHC is at least version 7.2, but the travis build only goes back to 7.4. If primitive is supposed to build with GHC 7.0, this should be done by travis since no one is going to want to do that by hand when examining PRs. Alternatively, if primitive only supports GHC 7.4 and up, the CPP should be removed. Either way, the haddocks and the github readme should be explicit about which versions of GHC are supported.

**Comment by RyanGlScott** [comment]
Ah, there do appear to be some [lingering `__GLASGOW_HASKELL__ >= 702` bits](https://github.com/haskell/primitive/search?utf8=%E2%9C%93&q=702&type=) lying around. We should remove those.

**Comment by andrewthad** [comment]
Sorry I forgot to get back to you on this.  It seems like you found the pre-7.2 shims  for copying ByteArrays.
