### ISSUE TITLE
Revise hackage bounds for primitive-0.6.1.0

### ISSUE THREAD

**Issue by andrewthad** [haskell/primitive#97]
This is a sort of odd request, but the dependencies of `primitive-0.6.1.0` are constrained too much. I don't actually need to use `primitive-0.6.1.0` for most stuff I work on, but I need to make sure certain libraries of mine are compatible with it because ghcjs pins me to that version in certain projects I'm working on. The upper bounds could be adjusted:

- `base < 4.12`
- `ghc-prim < 0.6`
- `transformers < 0.6`

**Comment by hvr** [comment]
@andrewthad btw, if this affects only your own private projects, there's a quicker way (as relaxing bounds on hackage requires a bit due diligence, especially for such an important package as `primitive`) : We've invested quite a bit of effort making `--allow-newer=`'s expression syntax richer and enable users: http://cabal.readthedocs.io/en/latest/nix-local-build.html#cfg-field-allow-newer

So you can e.g. write

```
allow-newer: primitive-0.6.1.0:base, primitive-0.6.1.0:ghc-prim, primitive-0.6.1.0:transformers
```

into your `cabal.project` file, to relax the upper bounds of that specific release, for those specific dependencies.

**Comment by andrewthad** [comment]
Thanks. That helps in my situation and should let me work around this issue.

**Comment by hvr** [comment]
@treeowl Sure; but there's different priorities attached to the primary (correctness) and secondary (completness of solutions) motivations for doing so. And the latter one specifically has sometimes additional concerns & costs attached which sometimes motivate suppressing that secondary motivation for the benefit of operational or strategic concerns. Just saying, that while the primary motivation is clear-cut, the secondary one isn't always as clear-cut.
